### ISSUE TITLE
Make it return t1 and t2 as well in case of parallel

### ISSUE THREAD

**Issue by piti118** [thegangtechnology/tg_math_lib#1]
https://github.com/thegangtechnology/tg_math_lib/blob/40e46b619eab9dfd156079f655322b0363058a63/src/tg_math_lib/geometry.py#L68

Just pick any valid two.

**Comment by thecheesynachos** [comment]
The latest commit is changed so that the value of t is always returned alongside distance. `return_t` tag is now removed.
